trigger:
- main


pool:
  vmImage: ubuntu-latest


variables:

  aksResourceGroup: flavorforge-rg
  aksClusterName: flavorforge-aks



stages:


- stage: ArgoCDDeploy

  displayName: "ArgoCD GitOps Deployment"


  jobs:


  - job: Deploy

    displayName: "Apply ArgoCD Application"


    steps:


    - checkout: self



    - task: AzureCLI@2

      displayName: "Connect to AKS"


      inputs:

        connectedServiceNameARM: flavorforge-azure-sc

        scriptType: bash

        scriptLocation: inlineScript


        inlineScript: |


          az aks get-credentials \
          --resource-group $(aksResourceGroup) \
          --name $(aksClusterName) \
          --overwrite-existing


          kubectl get nodes



    - bash: |

        echo "Applying ArgoCD Application"


        kubectl apply -f argocd/flavorforge-app.yaml



      displayName: "Create ArgoCD App"



    - bash: |

          echo "Waiting for ArgoCD Sync..."

          kubectl wait \
          --for=jsonpath='{.status.sync.status}'=Synced \
          application/flavorforge \
          -n argocd \
          --timeout=180s


          echo "ArgoCD Application Status"

          kubectl get applications -n argocd


          echo "Production Pods"

          kubectl get pods -n flavorforge

        displayName: "Verify ArgoCD Deployment"