sonar.issue.ignore.multicriteria=e1,e2,e3


# Docker COPY recursive warning
sonar.issue.ignore.multicriteria.e1.ruleKey=docker:S6470
sonar.issue.ignore.multicriteria.e1.resourceKey=frontend/Dockerfile


# Azure Pipeline task version warning
sonar.issue.ignore.multicriteria.e2.ruleKey=yaml:S6278
sonar.issue.ignore.multicriteria.e2.resourceKey=azure-pipelines.yml


# npm install lifecycle scripts warning
sonar.issue.ignore.multicriteria.e3.ruleKey=yaml:S4507
sonar.issue.ignore.multicriteria.e3.resourceKey=azure-pipelines.yml