sonar.projectKey=shettymalathib_flavorforge-azure-devsecops-capstone
sonar.organization=malathi-shetty

sonar.sources=backend,frontend,kubernetes
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**,**/*.test.js

sonar.sourceEncoding=UTF-8

sonar.issue.ignore.multicriteria=e1,e2,e3

sonar.issue.ignore.multicriteria.e1.ruleKey=docker:S6470
sonar.issue.ignore.multicriteria.e1.resourceKey=frontend/Dockerfile

sonar.issue.ignore.multicriteria.e2.ruleKey=yaml:S6278
sonar.issue.ignore.multicriteria.e2.resourceKey=azure-pipelines.yml

sonar.issue.ignore.multicriteria.e3.ruleKey=yaml:S4507
sonar.issue.ignore.multicriteria.e3.resourceKey=azure-pipelines.yml

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info