apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: flavorforge-qa

nameSuffix: -qa

patches:
  - path: backend-replica-patch.yaml
    target:
      kind: Deployment
      name: backend

  - path: frontend-replica-patch.yaml
    target:
      kind: Deployment
      name: frontend