apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: flavorforge
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/shettymalathib/flavorforge-azure-devsecops-capstone.git
    targetRevision: main
    path: kubernetes/overlays/prod


  destination:
    server: https://kubernetes.default.svc
    namespace: flavorforge


  syncPolicy:

    automated:
      prune: true
      selfHeal: true