apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: flavorforge

data:
  PORT: "3000"
  NODE_ENV: "production"
  CORS_ORIGIN: "http://104.45.175.93"
  APP_NAME: "FlavorForge Backend"
  APP_VERSION: "1.3"
  BUILD_VERSION: "1.3"