apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: flavorforge

type: Opaque

stringData:
 # Replace values before deployment - <YOUR_JWT_SECRET> & <YOUR_DATABASE_PASSWORD>
  JWT_SECRET: "replace-with-your-secret"
  DATABASE_PASSWORD: "replace-with-your-db-password"