apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: flavorforge

type: Opaque

stringData:
  JWT_SECRET: "replace-with-your-secret"
  DATABASE_PASSWORD: "replace-with-your-db-password"